# Generated by Django 5.0.4 on 2024-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="system", name="systemname",),
        migrations.AddField(
            model_name="system",
            name="name",
            field=models.CharField(default="h", max_length=50, verbose_name="name"),
        ),
    ]
