# Generated by Django 5.0.4 on 2024-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0002_remove_system_systemname_system_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="studentid",
            field=models.CharField(max_length=50, verbose_name="id"),
        ),
        migrations.AlterField(
            model_name="system",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
    ]
