# Generated by Django 5.0.4 on 2024-04-21 19:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0003_alter_student_studentid_alter_system_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="content"),
        ),
    ]
