# Generated by Django 5.0.4 on 2024-04-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0006_alter_message_attachement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.BooleanField(default=False, verbose_name="status"),
        ),
    ]
