# Generated by Django 5.0.4 on 2024-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0007_alter_message_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                blank=True, to="root.student", verbose_name="Students"
            ),
        ),
    ]
