# Generated by Django 5.0.4 on 2024-04-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0008_alter_group_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(to="root.student", verbose_name="Students"),
        ),
    ]
